language: python
dist: xenial

python:
  - "3.5"
  - "3.6"
  - "3.7"

cache: pip

install:
  - pip install tox-travis

script:
  - tox

after_success:
  - pip install codecov && codecov

notifications:
  email: false
