sudo: false

language: python

env:
  global:
    - NEWST_PYTHON=3.7

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy3"
  - "nightly"

install:
  - pip install -r requirements-dev.txt

cache: pip

script: tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d . | sed -e 's/pypypy/pypy/')

after_success:
  - |
    if [[ $TRAVIS_PYTHON_VERSION == $NEWEST_PYTHON && $TRAVIS_OS_NAME == 'linux' ]]; then
      pip install python-coveralls && coveralls
    fi

notification:
  email: false