sudo: false

language: python

env:
  global:
    - NEWST_PYTHON=nightly

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3"
  - "nightly"

install:
  - pip install -r requirements-dev.txt

cache: pip

install:
  - pip install tox-travis

script:
  - tox

after_success:
  - |
    if [[ $TRAVIS_PYTHON_VERSION == $NEWEST_PYTHON && $TRAVIS_OS_NAME == 'linux' ]]; then
      pip install python-coveralls && coveralls
    fi

notifications:
  email: false