language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

cache: pip

install:
  - pip install tox-travis
  - python ./scripts/install_z3.py

script:
  - tox

jobs:
  include:
    - stage: codecov
      python: "3.6"
      script:
        - tox
        - pip install codecov && codecov --token=$CODECOV_TOKEN

notifications:
  email: false
